name: Tree Sitter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parser: ["parsers/tree-sitter-minizinc"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{matrix.parser}}
      - name: Build the parser
        run: npm run build --if-present
        working-directory: ${{matrix.parser}}
      - name: Run parser tests
        run: npm test
        working-directory: ${{matrix.parser}}
      - name: Check if generated file are up-to-date
        run: git diff --exit-code
      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: tree-sitter
          path: |
            ${{matrix.parser}}/src
            ${{matrix.parser}}/bindings/node
